#!/bin/bash
#P4CONFIG=".p4config" p4 "$@"

if [ "$1" = "" ]; then	
	echo "Usage: $0 [SUBDIR] DEPOTPATH [FILTER_DIR1 [FILTER_DIR2 [...]]]"
	echo "The command creates a new p4 workspace from the path specified to the current working directory"
	exit 1
fi

if [ "$P4USER" = "" ]; then
	echo "P4USER is not specified"
	exit 1
fi

# First argument may optionally denote the client subdirectory to which we should map the workspace
# We can determine if it is depot path by its beginning: If is starts with double slash, it is a depot path, otherwise it is a local subdir
if [[ "$1" =~ ^\/\/.* ]]; then
	DEPOT=$1
	SUBDIR="${DEPOT/\/\//}/Workspace"
	shift
else
	SUBDIR=$1
	DEPOT=$2
	shift
	shift
fi 

echo "SUBDIR=$SUBDIR"
echo "DEPOT=$DEPOT"

mkdir -p "$SUBDIR"
cd "$SUBDIR"

DEPOTX=${DEPOT//\//-}
DIR=`pwd`
DIRX=${DIR//[\/#@]/-}
HOST=`hostname`

CLIENT="${P4USER}_${HOST}_${DEPOTX}_${DIRX}"

P4EDITOR=nano

echo INFO: Creating client $CLIENT



if [[ "$1" == "" ]]; then
	# Try to search for the depot path in P4 streams
	STREAMSPEC=`pp4 streams | grep "Stream $DEPOT "`
	if [ "$STREAMSPEC" != "" ]; then
		STREAMDEF="Stream:	$DEPOT"
		echo "INFO: $DEPOT is a stream."
	else
		STREAMDEF="# Not a stream"
		echo "INFO: $DEPOT is not a stream."
	fi
else
	STREAMDEF="# Stream not applicable"
	echo "INFO: $DEPOT may or may not be a stream, but are not registering it as such, because view is overriden."
fi

# Some character must be escaped for P4

DIR=${DIR//%/%25}
DIR=${DIR//@/%40}
DIR=${DIR//#/%23}
DIR=${DIR//\*/%2A}

cat > .clientspec << END
Client:	$CLIENT
Owner:	$P4USER
Host:	$HOST
Description: Created by PP4 on behalf of $P4USER.
Root:	$DIR
Options:	noallwrite noclobber nocompress unlocked nomodtime normdir
SubmitOptions:	submitunchanged
LineEnd:	local
$STREAMDEF
View:
END

cat .clientspec

if [[ "$1" == "" ]]; then
	echo -e "\t$DEPOT/... //$CLIENT/..." >> .clientspec
fi

while [[ "$1" != "" ]]; do
	echo -e "\t$DEPOT/$1/... //$CLIENT/$1/..." >> .clientspec
	shift
done
		

cat .clientspec | pp4 client -i

pp4 autoconfig -c $CLIENT

#pp4 client -S $DEPOT $CLIENT
