#!/bin/bash

CL=$1
CLIENT=`workspace_from_changelist $CL`
DP=`stream_from_workspace $CLIENT`
PWD=`pwd`

PENDING=`pp4 describe -s $CL | head -n1 | grep pending`

if [ "$PENDING" = "" ]; then
	# Submitted changlist -> create patch against previous revision
	pp4 diff2 -u "$DP/...@$((CL-1))" "$DP/...@$CL" | sed "s|$DP|.|"
else
	# Pending changlist -> is it in curent workspace?
	CURRENT_CLIENT=`get_current_workspace`
	if [ "$CURRENT_CLIENT" = "$CLIENT" ]; then
		# Current workspace -> create patch from the actual files in it
		pp4 opened -c $CL | sed -e 's/#.*//' | pp4 -x - diff -du | sed "s|$DP|.|" | sed "s|$PWD|.|"
	else
		# Another workspace -> create patch from shelved files (if any)
		pp4 describe -du4 -S $CL | awk 'p; /Differences .../ {p=1};' | sed 's/^==== \([^#]*\)#.*$/+++ \1\
--- \1/' | sed "s|$DP|.|" | sed "s|$PWD|.|"
		exit 1
	fi
fi

